FROM nginx:latest
RUN mkdir -p /usr/src/app
RUN chmod -R 755 /usr/src/app
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/index.html /usr/src/app/index.html
COPY ./server/public /usr/src/app